### ISSUE TITLE
All functions occasionally produce arbitrary hashes given the same input

### ISSUE THREAD

**Issue by kaxap** [kpdemetriou/highwayhash-cffi#1]
Tested on 
- Python 3.7 (Anaconda build, Windows 10)
- Python 3.6 (Centos 7)

We have integrated HighwayHash into our ETL which has services on Java, Golang and Python. Python services use this library. The problem is that messages coming to/from Python services (which use this lib) occasionally had hash mismatches. 

Upon closer inspection, the library functions appear to result in arbitrary hashes given the same input.

**Comment by kpdemetriou** [comment]
Good catch; this has been rectified as of version 0.1.6 available on PyPI (and reflected in this repo).
